# Generated by Django 5.2 on 2025-04-06 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0003_alter_love_image_alter_love_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/love/', validators=[django.core.validators.FileExtensionValidator(['.mp4', '.mkv', '.avi', '.mov', '.flv', '.wmv', '.webm', '.mpeg', '.mpg', '.3gp', '.ogv', '.rm', '.vob', '.ts', '.m4v', '.mts'])]),
        ),
    ]
