# Generated by Django 5.1.7 on 2025-03-30 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, null=True, size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/projects')),
                ('github', models.CharField(blank=True, max_length=500, null=True)),
                ('demo', models.CharField(blank=True, max_length=300, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
